/*-----------------------------------------------------------------------------
 * Syneight - A soft-realtime transaction monitor.
 * Copyright (C) 2003-2004 The Syneight Group.
 *
 * TODO: License.
 *---------------------------------------------------------------------------*/

/**
 * @file TODO
 *
 * @author TODO
 * @author $Author: esdentem $
 *
 * @version $Id: binary_trace.hpp 1053 2005-06-07 12:14:38Z esdentem $
 *
 * @brief TODO
 *
 * TODO: Long description.
 *
 * @note TODO
 *
 * @todo TODO
 */

#ifndef SYNEIGHT__ANNOTATION__BITS__BINARY_TRACE_HPP
#define SYNEIGHT__ANNOTATION__BITS__BINARY_TRACE_HPP

#include <syneight/base/annotation/base/trace.hpp>

////////////////////////////////////////////////////////////////////////////////

#if SYNEIGHT__SWITCH__BUILD_LEVEL == 2
#  define SYNEIGHT__AUD__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,AUD,(WHAT))
#  define SYNEIGHT__AUD__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,AUD,(WHAT),(CATEGORY))
#  define SYNEIGHT__AUD__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,AUD,(WHAT),(NR))
#  define SYNEIGHT__AUD__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,AUD,(WHAT),(NR),(CATEGORY))
#else 
#  define SYNEIGHT__AUD__BINARY_TRACE(WHAT)                 ((void)0)
#  define SYNEIGHT__AUD__BINARY_TRACE1(WHAT,CATEGORY)       ((void)0)
#  define SYNEIGHT__AUD__BINARY_TRACE_NR(WHAT,NR)           ((void)0)
#  define SYNEIGHT__AUD__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)
#endif

////////////////////////////////////////////////////////////////////////////////

#if SYNEIGHT__SWITCH__BUILD_LEVEL > 0
#  define SYNEIGHT__DEB__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,DEB,(WHAT))
#  define SYNEIGHT__DEB__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,DEB,(WHAT),(CATEGORY))
#  define SYNEIGHT__DEB__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,DEB,(WHAT),(NR))
#  define SYNEIGHT__DEB__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,DEB,(WHAT),(NR),(CATEGORY))
#else 
#  define SYNEIGHT__DEB__BINARY_TRACE(WHAT)                 ((void)0)
#  define SYNEIGHT__DEB__BINARY_TRACE1(WHAT,CATEGORY)       ((void)0)
#  define SYNEIGHT__DEB__BINARY_TRACE_NR(WHAT,NR)           ((void)0)
#  define SYNEIGHT__DEB__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)
#endif

////////////////////////////////////////////////////////////////////////////////

#if SYNEIGHT__SWITCH__BUILD_LEVEL > -1

#  define SYNEIGHT__PRO__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,PRO,(WHAT))
#  define SYNEIGHT__EME__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,EME,(WHAT))
#  define SYNEIGHT__ALE__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,ALE,(WHAT))

#  define SYNEIGHT__PRO__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,PRO,(WHAT),(CATEGORY))
#  define SYNEIGHT__ALE__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,ALE,(WHAT),(CATEGORY))
#  define SYNEIGHT__EME__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,EME,(WHAT),(CATEGORY))

#  define SYNEIGHT__PRO__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,PRO,(WHAT),(NR))
#  define SYNEIGHT__EME__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,EME,(WHAT),(NR))
#  define SYNEIGHT__ALE__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,ALE,(WHAT),(NR))

#  define SYNEIGHT__PRO__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,PRO,(WHAT),(NR),(CATEGORY))
#  define SYNEIGHT__ALE__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,ALE,(WHAT),(NR),(CATEGORY))
#  define SYNEIGHT__EME__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,EME,(WHAT),(NR),(CATEGORY))

#else 

#  define SYNEIGHT__PRO__BINARY_TRACE(WHAT)              ((void)0)
#  define SYNEIGHT__ALE__BINARY_TRACE(WHAT)              ((void)0)
#  define SYNEIGHT__EME__BINARY_TRACE(WHAT)              ((void)0)

#  define SYNEIGHT__PRO__BINARY_TRACE1(WHAT,CATEGORY)    ((void)0)
#  define SYNEIGHT__ALE__BINARY_TRACE1(WHAT,CATEGORY)    ((void)0)
#  define SYNEIGHT__EME__BINARY_TRACE1(WHAT,CATEGORY)    ((void)0)

#  define SYNEIGHT__PRO__BINARY_TRACE_NR(WHAT,NR)           ((void)0)
#  define SYNEIGHT__EME__BINARY_TRACE_NR(WHAT,NR)           ((void)0)
#  define SYNEIGHT__ALE__BINARY_TRACE_NR(WHAT,NR)           ((void)0)

#  define SYNEIGHT__PRO__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)
#  define SYNEIGHT__ALE__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)
#  define SYNEIGHT__EME__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)

#endif

////////////////////////////////////////////////////////////////////////////////

#if SYNEIGHT__SWITCH__TEST_ANNOTATIONS == 1
#  define SYNEIGHT__TES__BINARY_TRACE(WHAT)                 SYNEIGHT__INTERNAL__BINARY_TRACE(BINARY_TRACE,TES,(WHAT))
#  define SYNEIGHT__TES__BINARY_TRACE1(WHAT,CATEGORY)       SYNEIGHT__INTERNAL__BINARY_TRACE1(BINARY_TRACE,TES,(WHAT),(CATEGORY))
#  define SYNEIGHT__TES__BINARY_TRACE_NR(WHAT,NR)           SYNEIGHT__INTERNAL__BINARY_TRACE_NR(BINARY_TRACE,TES,(WHAT),(NR))
#  define SYNEIGHT__TES__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) SYNEIGHT__INTERNAL__BINARY_TRACE_NR1(BINARY_TRACE,TES,(WHAT),(NR),(CATEGORY))
#elif SYNEIGHT__SWITCH__TEST_ANNOTATIONS == 0
#  define SYNEIGHT__TES__BINARY_TRACE(WHAT)                 ((void)0)
#  define SYNEIGHT__TES__BINARY_TRACE1(WHAT,CATEGORY)       ((void)0)
#  define SYNEIGHT__TES__BINARY_TRACE_NR(WHAT,NR)           ((void)0)
#  define SYNEIGHT__TES__BINARY_TRACE_NR1(WHAT,NR,CATEGORY) ((void)0)
#endif

#endif
// vim:ts=4:sw=4
