#ifndef SYNEIGHT__TEST__XMATRIX__NAMESPACE_HPP
#define SYNEIGHT__TEST__XMATRIX__NAMESPACE_HPP

#define SYNEIGHT__BEGIN__NAMESPACE__XMATRIX namespace xmatrix {
#define SYNEIGHT__END__NAMESPACE__XMATRIX   }

SYNEIGHT__BEGIN__NAMESPACE__XMATRIX;
SYNEIGHT__END__NAMESPACE__XMATRIX;

#endif
// vim:ts=4:sw=4
